# Generated by Django 4.2.3 on 2023-07-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mfa_required", models.BooleanField(default=False)),
                (
                    "address_street",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_lga",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("address_country", models.CharField(default="NG", max_length=20)),
                (
                    "address_postal_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
